### ISSUE TITLE
Compatibility for Dock / Injection with Ventura 13.1

### ISSUE THREAD

**Issue by jonathanwilner** [FelixKratz/yabai#10]
Hi - I love your branch of Yabai! I'm not confident in my ability to cherry pick the 13.1 sa injection update from koekeishiya's master & merge it with your branch. Is it possible that you could add that into yours? 

Thanks!

**Comment by jonathanwilner** [comment]
Thank you !

**Comment by jonathanwilner** [comment]
Hi - sorry to comment on your closed issue, but I'm unable to load the Scripting addition still, even with a fresh install from your changes. I am sure it's user error on my end on 13.1. I'll keep plugging away, but if you have any idea of where I might be going wrong, I'd love a pointer in the right direction. Thanks!

**Comment by FelixKratz** [comment]
Try these commands in order:
```bash
brew services stop yabai
brew uninstall yabai
brew services stop fyabai
brew uninstall fyabai
killall yabai
brew tap FelixKratz/formulae
brew install fyabai --head
sudo yabai --uninstall-sa
sudo yabai --load-sa
brew services start fyabai
```

**Comment by jonathanwilner** [comment]
Thank you ! I forgot to do --uninstall-sa. :-(
