### ISSUE TITLE
Front window borders can't cover inactive window borders

### ISSUE THREAD

**Issue by cxa** [FelixKratz/yabai#11]
Thanks for the excellent fork!

Any idea on this problem? as below, the front window with red borders, can not cover below black borders:

<img width="1920" alt="Screenshot 2023-02-15 at 11 55 52" src="https://user-images.githubusercontent.com/32127/218925347-97907b09-cb5c-4e91-b608-af1d78e70d2a.png">

**Comment by FelixKratz** [comment]
This is because I have hidden the wibdows yabai creates from the macOS window manager process and it must be disabled for ordering to work properly:
```bash
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
```
This is needed for smoother animations, as the system window manager creates a flicker when it internally reorders windows.

**Comment by cxa** [comment]
Thanks.
