### ISSUE TITLE
Closing a stacked window changes focus

### ISSUE THREAD

**Issue by Bellavene** [FelixKratz/yabai#12]
Closing a stacked window changes focus from stack to window before it.

**Comment by FelixKratz** [comment]
I dont regularly use stacks, the change for the natural next window focus is here: https://github.com/FelixKratz/yabai/commit/0739769b610f59a8cf846208c8615f807836d2f2
you will have to adapt the function `window_manager_find_natural_next_window` such that it focuses the next window in a stack instead if the closed window is contained in a stack
