### ISSUE TITLE
PR to yabai?

### ISSUE THREAD

**Issue by b4rlw** [FelixKratz/yabai#15]
Do you have any intention to PR your patches to yabai?
Would love to see the ultrawide and animation patches in particular as part of the core utility.

**Comment by FelixKratz** [comment]
No, the author of yabai has stated that the project does not welcome pull requests.

I think the current yabai scripting possibilities are not powerful enough and too slow, but I believe the maintainer of yabai has already created two issues himself that address this. Once the scripting is more powerful the ultrawide patches are not needed anymore and can be implemented in a script.

**Comment by b4rlw** [comment]
Ah, good to know. Thanks for the information!

**Comment by AlJohri** [comment]
>but I believe the maintainer of yabai has already created two issues himself that address this

linking the relevant upstream issues here:
- https://github.com/koekeishiya/yabai/issues/1606
- https://github.com/koekeishiya/yabai/issues/1605
