### ISSUE TITLE
Disabling padding for ultrawide

### ISSUE THREAD

**Issue by nyanSpruk** [FelixKratz/yabai#16]
I love using your fork, at least most of the features and would like to know if there is an option to disable padding for ultrawide monitors?
If this is not currently implemented, would it be possible to have it implemented?

Edit:
To be more specific. I do not want to disable gaps, but I want to have normal gaps like on normally sized monitors.

Added image example
![image](https://user-images.githubusercontent.com/14331235/232248078-a290325a-db38-4453-b67d-2d085e4a820b.png)

**Comment by FelixKratz** [comment]
I have made it such that this is deactivated by default now.
