### ISSUE TITLE
Does top padding effect aspect ratio?

### ISSUE THREAD

**Issue by cbackas** [FelixKratz/yabai#17]
I saw your Reddit clip of the way things stay centered on your ultrawide, and it was very cool. I don't use an ultrawide, but I have a 48" 4K monitor on my desk. The top of the screen is a bit high, so I prefer not to have Yabai place windows up there. Currently, I accomplish this by setting the top padding on the main display using the `external_bar` Yabai setting, adding 500px up there to keep my windows at a manageable height.

When the aspect ratio is calculated and compared to `auto_padding_min_aspect`, is the top padding taken into account when calculating that ratio? I skimmed through some of the code, and my answer landed on "maybe," but C isn't a language I've really ever used, and I haven't spent much time in this codebase. I would love to know if I can trick Fyabai into treating my screen as an ultrawide (ideally without having to fork and make further changes :P).

I currently have a scripted version that attempts to dynamically set the vertical padding based on the number of windows, but it's a bit clunky visually since you can see Yabai place the windows before the Yabai event triggers the script, which then adjusts the windows again. I saw you mentioned in https://github.com/FelixKratz/yabai/issues/15#issuecomment-1483823470 that there is a better scripting addition coming to Yabai. I couldn't find the GitHub issues you were referring to when I checked last night; do you have links to them? I would love to follow that.

Thanks!

**Comment by FelixKratz** [comment]
Hi, the bounds I use for checking the aspect ratio are the real display bounds from `CGDisplayBounds`, so no the top padding does not change aspect ratio.

You can change the aspect minimum aspect ratio however and the target height / width of the windows. These are the defaults:
```bash
yabai -m config auto_padding off
yabai -m config auto_padding_min_aspect 2.33
yabai -m config auto_padding_width 840
yabai -m config auto_padding_height 1200
```

The issues I was referencing are here: https://github.com/koekeishiya/yabai/issues/1606 and https://github.com/koekeishiya/yabai/issues/1605
