### ISSUE TITLE
Two borders per window

### ISSUE THREAD

**Issue by Bellavene** [FelixKratz/yabai#20]
Is there any reason now to draw two borders per window? It just flickers top border when animations are on.
Anyway, thank you. I really enjoy your version of animations.

**Comment by FelixKratz** [comment]
I am not sure I understand what you mean?
This is what it looks like for me:

https://github.com/FelixKratz/yabai/assets/22680421/20a192fe-3311-4906-9997-75798c5fb19c

**Comment by Bellavene** [comment]
Your border is much smaller than mine. Mine looks like this 
<img width="1440" alt="Screenshot 2023-09-05 at 16 29 44" src="https://github.com/FelixKratz/yabai/assets/77557804/09eff947-09cd-4f4e-ade4-0dccdbe0a479">

Thats why I see the second border on top of the window, which dissapears on every animation.

**Comment by FelixKratz** [comment]
Do you have SIP disabled and disabled the apple window manager?
```bash
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist > /dev/null 2>&1 &
```

**Comment by Bellavene** [comment]
Ah, got it. I don't disable window manager, because I need the ability to minimize the window.
