### ISSUE TITLE
Assertion Failed on Border

### ISSUE THREAD

**Issue by typkrft** [FelixKratz/yabai#3]
`Assertion failed: (corner_height >= 0 && 2 * corner_height <= CGRectGetHeight(rect)), function CGPathAddRoundedRect, file CGPath.cc, line 498.`

Was going to checkout what changes have been made to this fork, but trying to run it with borders turned on with your `yabairc` seems to fail for me. Not sure if I'm missing a setting or how to debug this further. Installed `--head` via brew.

All the best!

**Comment by FelixKratz** [comment]
It seems you have some very small windows ^^ thats why the assert fails in `CGPathAddRoundedRect`. I have checked for small windows explicitly and don't draw a border for them now. Basically twice the corner radius of a rounded rect can not be larger than the width or the height of the rounded rect in total.

**Comment by typkrft** [comment]
Nice! Thanks!
